---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boor-agent
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boor-agent
subjects:
  - kind: ServiceAccount
    name: boor-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
