---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    fluxcd.io/automated: 'true'
  labels:
    app: door-agent
  {{- range $key, $value := .Values.doorAgent.labels }}
    {{ $key  }}: {{ $value  }}
  {{- end }}
  name: door-agent
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: door-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: door-agent
      {{- range $key, $value := .Values.doorAgent.labels }}
        {{ $key  }}: {{ $value  }}
      {{- end }}
    spec:
    {{- if .Values.defaultCluster }}
      initContainers:
        - name: door-api-check
          image: {{ .Values.global.doorAPI.heathCheck.image.name }}:{{ .Values.global.doorAPI.heathCheck.image.version }}
          command: ["/bin/sh","-c"]
          args:
            - |
              until curl -s -f -o /dev/null "{{ include "door-agent.doorAPIUrl" . }}{{ .Values.global.doorAPI.heathCheck.endpoint }}"
              do
                echo door API {{ include "door-agent.doorAPIUrl" . }}{{ .Values.global.doorAPI.heathCheck.endpoint }} unvailable `date`
                sleep 10
              done
              echo Successed: `date`
    {{- end }}
      {{- if .Values.doorAgent.hostAliases }}
      hostAliases:
        {{- toYaml .Values.doorAgent.hostAliases | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.doorAgent.image.name }}:{{ .Values.doorAgent.image.version }}
          imagePullPolicy: Always
          name: door-agent
          resources:
          {{- if hasKey .Values.doorAgent "resources" }}
          {{- toYaml .Values.doorAgent.resources | nindent 12 }}
          {{- end }}
          env:
            - name: METRICS_SERVER_RATE_LIMIT
              value: {{ .Values.doorAgent.rateLimit.METRICS_SERVER_RATE_LIMIT | quote }}
            - name: METRICS_SERVER_RATE_LIMIT_DURATION_MS
              value: {{ .Values.doorAgent.rateLimit.METRICS_SERVER_RATE_LIMIT_DURATION_MS | quote }}
            - name: METRICS_SERVER_REQUEST_TIMEOUT_SECOND
              value: {{ .Values.doorAgent.rateLimit.METRICS_SERVER_REQUEST_TIMEOUT_SECOND | quote }}
            - name: IN_CLUSTER
              value: "true"
            - name: DOOR_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KAFKA_TlS_ENABLED
              value: "true"
            - name: KAFKA_BROKERS
              value: {{ .Values.doorAgent.kafka.brokers }}
            - name: KAFKA_CA_CERT
              {{- if .Values.defaultCluster }}
              value: /kafka/ca/ca.crt
              {{- else }}
              value: /kafka/user/ca.crt
              {{- end }}
            - name: KAFKA_CLIENT_CERT
              value: /kafka/user/user.crt
            - name: KAFKA_CLIENT_KEY
              value: /kafka/user/user.key
            - name: PIPELINE_CPU_LIMIT
              value: {{ .Values.doorAgent.pipeline.cpuLimit | quote}}
            - name: PIPELINE_MEMORY_LIMIT
              value: {{ .Values.doorAgent.pipeline.memoryLimit | quote}}
            - name: PIPELINE_CPU_REQUEST
              value: {{ .Values.doorAgent.pipeline.cpuRequest | quote}}
            - name: PIPELINE_MEMORY_REQUEST
              value: {{ .Values.doorAgent.pipeline.memoryRequest | quote}}
            - name: PIPELINE_STORAGE_LIMIT
              value: {{ .Values.doorAgent.pipeline.storageLimit | quote}}
            - name: PIPELINE_STORAGE_REQUEST
              value: {{ .Values.doorAgent.pipeline.storageRequest | quote }}
            - name: LICENCE
              valueFrom:
                secretKeyRef:
                  name: {{ include "door-agent.licenceSecret" . }}
                  key: uuid
          volumeMounts:
            - name: kafka-user
              mountPath: /kafka/user
            {{- if .Values.defaultCluster }}
            - name: kafka-ca
              mountPath: /kafka/ca
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: door-agent
      volumes:
        - name: kafka-user
          secret:
            {{- if .Values.defaultCluster }}
            secretName: door-kafka-superadmin
            {{- else }}
            secretName: {{ include "door-agent.licenceSecret" . }}
            {{- end }}
        {{- if .Values.defaultCluster }}
        - name: kafka-ca
          secret:
            secretName: door-kafka-cluster-cluster-ca-cert
        {{- end }}
