apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
    component: database
  name: keycloak-postgresql
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
      component: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
        component: database
      name: keycloak-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USERNAME
              name: keycloak-db-secret
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: keycloak-db-secret
        - name: POSTGRESQL_DATABASE
          value: root
        image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: keycloak-postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: keycloak-postgresql-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: keycloak-postgresql-claim
        persistentVolumeClaim:
          claimName: keycloak-postgresql-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: keycloak
  name: keycloak-postgresql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem

---

apiVersion: v1
data:
  POSTGRES_EXTERNAL_ADDRESS: a2V5Y2xvYWstZGIuY25vLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  POSTGRES_EXTERNAL_PORT: NTQzMgo=
  POSTGRES_SUPERUSER: dHJ1ZQo=
  POSTGRES_DATABASE: cm9vdA==
  POSTGRES_HOST: a2V5Y2xvYWstcG9zdGdyZXNxbA==
  POSTGRES_PASSWORD: Y2xvdWQta2V5Y2xvYWstYXNBbFo4VzZ1UzRQTnpxNmk0RXIxbDVJdTFVdlhERE9SZEttM1M4eFhncz0=
  POSTGRES_USERNAME: a2V5Y2xvYWs=
  POSTGRES_VERSION: MTA=
kind: Secret
metadata:
  labels:
    app: keycloak
  name: keycloak-db-secret
type: Opaque

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: keycloak
    component: database
  sessionAffinity: None
  type: ClusterIP
