source:
  kind: ConfigMap
  name: cno-images-config
  fieldPath: data.KEYCLOAK_OPERATOR_IMAGE
targets:
- select:
    kind: Deployment
    name: keycloak-operator
  fieldPaths:
  - spec.template.spec.containers.[name=keycloak-operator].image