apiVersion: v1
kind: ServiceAccount
metadata:
  name: door-onboarding-operator
  namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: door-quotas
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: "50"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: door-onboarding-operator
subjects:
  - kind: ServiceAccount
    name: door-onboarding-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: door-onboarding-operator
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.doorOnboarding.labels }}
    {{ $key  }}: {{ $value  }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door-onboarding-operator
  template:
    metadata:
      labels:
        app: door-onboarding-operator
      {{- range $key, $value := .Values.doorOnboarding.labels }}
        {{ $key  }}: {{ $value  }}
      {{- end }}
    spec:
      serviceAccountName: door-onboarding-operator
      containers:
        - name: door-onboarding-operator
          image: {{ .Values.doorOnboarding.image.name }}:{{ .Values.doorOnboarding.image.version }}
          imagePullPolicy: Always
          resources:
          {{- if hasKey .Values.doorOnboarding "resources" }}
          {{- toYaml .Values.doorOnboarding.resources | nindent 12 }}
          {{- end }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: DOOR_NAMESPACE
              value:  {{ .Release.Namespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "door-onboarding-operator"

