apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cno-kafka-cluster
spec:
  kafka:
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    - name: external
      port: 9094
      type: route
      tls: true
      authentication:
        type: tls
      configuration:
        bootstrap:
          host: bootstrap-cno.$(DOMAIN)
        brokers:
        - broker: 0
          host: broker-0-cno.$(DOMAIN)
        - broker: 1
          host: broker-1-cno.$(DOMAIN)
        - broker: 2
          host: broker-2-cno.$(DOMAIN)
