apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../loadbalancer/psp

patchesStrategicMerge:
- cno-ui-deployment-patch.yaml
- keycloak-postgresql-patch.yaml
resources:
- cno-scc.yaml