# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     app: door-apim-operator
#     app.kubernetes.io/name: namespace
#     app.kubernetes.io/instance: system
#     app.kubernetes.io/component: manager
#     app.kubernetes.io/created-by: door-apim-operator
#     app.kubernetes.io/part-of: door-apim-operator
#     app.kubernetes.io/managed-by: kustomize
#   name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: door-apim-operator
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.doorAPIM.labels }}
    {{ $key  }}: {{ $value  }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: door-apim-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: door-apim-operator
      {{- range $key, $value := .Values.doorAPIM.labels }}
        {{ $key  }}: {{ $value  }}
      {{- end }}
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: {{ .Values.doorAPIM.image.name }}:{{ .Values.doorAPIM.image.version }}
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
        {{- if hasKey .Values.doorAPIM "resources" }}
        {{- toYaml .Values.doorAPIM.resources | nindent 12 }}
        {{- end }}
        env:
        {{- if hasKey .Values.doorAPIM "envs" }}
        {{- toYaml .Values.doorAPIM.envs | nindent 12 }}
        {{- end }}
      serviceAccountName: door-apim-operator
      terminationGracePeriodSeconds: 10