apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cno-notification
  name: cno-notification
spec:
  host: cno-notification.apps.openshifttest.beopenit.com
  to:
    kind: Service
    name: cno-notification
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge