apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cno-api
  name: cno-api
spec:
  host: cno-api.apps.openshifttest.beopenit.com
  to:
    kind: Service
    name: cno-api
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge