{{- if .Values.agentConfig.defaultCluster }}
apiVersion: v1
data:
  uuid: {{ include "cno-chart.clusterAgentUuid" . | b64enc }}
kind: Secret
metadata:
  name: {{ include "cno-chart.licenceSecret" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
