apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: cno-kafka-superadmin
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: cno-kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls: []
