{{- if not (hasKey .Values.keycloakConfig.admin "secret") }}
apiVersion: v1
data:
  ADMIN_PASSWORD: {{ .Values.keycloakConfig.admin.password | b64enc }}
  ADMIN_USERNAME: {{ .Values.keycloakConfig.admin.username | b64enc }}
kind: Secret
metadata:
  name: cno-keycloak-admin
  namespace: {{ .Release.Namespace }}
{{- end }}
