apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cno-kafka-cluster
spec:
  kafka:
    template:
      pod:
        imagePullSecrets:
        - name: $(IMAGE_PULL_SECRETS_NAME)
    image: $(STRIMZI_KAFKA_IMAGE)
<<<<<<< HEAD
    version: 3.0.0
=======
    version: 2.5.0
>>>>>>> 2ad8d51d600200a23a31fe70a7bef1d68dcdeb06
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
<<<<<<< HEAD
          disableTlsHostnameVerification: true
        configuration:
          class: nginx
=======
        configuration:
>>>>>>> 2ad8d51d600200a23a31fe70a7bef1d68dcdeb06
          bootstrap:
            host: bootstrap-cno.$(DOMAIN)
          brokers:
          - broker: 0
            host: broker-0-cno.$(DOMAIN)
          - broker: 1
            host: broker-1-cno.$(DOMAIN)
          - broker: 2
            host: broker-2-cno.$(DOMAIN)
    authorization:
      type: simple
      superUsers:
        - CN=cno-kafka-superadmin
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
<<<<<<< HEAD
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.0"
      log.message.format.version: "3.0"
=======
      log.message.format.version: "2.5"
>>>>>>> 2ad8d51d600200a23a31fe70a7bef1d68dcdeb06
    storage:
      type: ephemeral
  zookeeper:
    template:
      pod:
        imagePullSecrets:
        - name: $(IMAGE_PULL_SECRETS_NAME)
    image: $(STRIMZI_KAFKA_IMAGE)
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    template:
      pod:
        imagePullSecrets:
        - name: $(IMAGE_PULL_SECRETS_NAME)
    topicOperator:
      image: $(STRIMZI_OPERATOR_IMAGE)
    userOperator:
      image: $(STRIMZI_OPERATOR_IMAGE)
    tlsSidecar:
      image: $(STRIMZI_KAFKA_IMAGE)
