source:
  kind: ConfigMap
  name: cno-images-config
  fieldPath: data.STRIMZI_KAFKA_IMAGE
targets:
- select:
    kind: kafka
    name: cno-kafka-cluster
  fieldPaths:
  - spec.entityOperator.tlsSidecar.image