source:
  kind: ConfigMap
  name: cno-images-config
  fieldPath: data.MYSQL_OPERATOR_ORCHESTRATOR_IMAGE
targets:
- select:
    kind: StatefulSet
    name: mysql-operator
  fieldPaths:
  - spec.template.spec.containers.[name=orchestrator].image