apiVersion: v1
kind: ServiceAccount
metadata:
  name: cno-agent
imagePullSecrets:
- name: $(IMAGE_PULL_SECRETS_NAME)
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cno-agent
subjects:
- kind: ServiceAccount
  name: cno-agent
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io