apiVersion: v1
kind: Service
metadata:
  name: cno-ui
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: cno-api
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: cno-kafka-cluster-kafka-external-bootstrap
spec:
  ports:
  - name: tcp-external
    port: 9094
    protocol: TCP
    targetPort: 9094
  sessionAffinity: None
  type: NodePort
