global:
  # door-api config
  doorAPI:
    labels:
      # will be applied to pods and deployment
    protocol: http
    # internalServiceName: door-api-svc
    externalUrl: https://api.door.io
    heathCheck:
      image:
        name: docker.io/nginxinc/nginx-unprivileged
        version: latest
      endpoint: /api/v1/healthy
# set defaultCluster=true if cluster content control plane
defaultCluster: false
defaultClusterType: gke
doorOnboarding:
  labels:
    # will be applied to pods and deployment
  image:
    name: docker.io/beopenit/onboarding-operator-kubernetes
    version: v2.4.00
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  #   limits:
  #     cpu: 1
  #     memory: 1Gi
doorCD:
  labels:
    # will be applied to pods and deployment
  # maxStagingReplicas: -22
  envs:
    - name: MAX_STAGING_REPLICAS
      value: "-1"
    - name: DOOR_AUTO_GEN_LISTENER
      value: "false"
    - name: INSECURE_REGISTRIES
      value: ""
    - name: DEFAULT_INTERNAL_GATEWAY_DOMAIN
      value: door.local
    - name: DEFAULT_TIMEOUT
      value: 30s
  image:
    name: docker.io/beopenit/door-cd-operator
    version: v2.4.02
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 2
  #     memory: 2Gi
doorAPIM:
  labels:
    # will be applied to pods and deployment
  envs:
    - name: WATCH_NAMESPACE
      value: ""
  image:
    name: docker.io/doorcloud/apim-operator
    version: v2.0.5
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 2
  #     memory: 2Gi
doorHelm:
  labels:
    # will be applied to pods and deployment
  # maxStagingReplicas: -22
  image:
    name: beopenit/door-helm
    version: v2.4.01
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 2Gi
doorAgent:
  labels:
    # will be applied to pods and deployment
  metricServer: true
  image:
    name: docker.io/beopenit/door-agent
    version: v2.4.08
  rateLimit:
    METRICS_SERVER_RATE_LIMIT_DURATION_MS: 10
    METRICS_SERVER_RATE_LIMIT: 500
    METRICS_SERVER_REQUEST_TIMEOUT_SECOND: 30
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  #   limits:
  #     cpu: 1
  #     memory: 1Gi
  kafka:
    brokers: door-kafka-cluster-kafka-external-bootstrap:9094
  licence:
    uuid: aa
    key: |
      my-key
    crt: |
      my-crt
    ca: |
      my-ca
    # Overwrite licence secret: set keys uuid, user.key, user.crt and ca.crt
    # secret:
    #   name: my-licence

monitoring:
  include: true
  pvcSize: 15Gi
  # storageClassName: gp2
  # accessMode: ReadWriteOne

doorApiGateway:
  internal: 
    enabled: true
    type: clusterIP
    nodeSelector: node-role.kubernetes.io/ingress-door
    tolerationsKey: ingress-door
    annotations:
      service.beta.kubernetes.io/load-balancer-type: "Internal"
      service.beta.kubernetes.io/external-traffic-policy: "Local"
      service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    labels:
      app: door-apigateway-internal
  external:
    enabled: false
    type: loadBalancer
    nodeSelector: node-role.kubernetes.io/ingress-door
    tolerationsKey: ingress-door
    annotations:
      service.beta.kubernetes.io/load-balancer-type: "Internal"
      service.beta.kubernetes.io/external-traffic-policy: "Local"
      service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    labels:
      app: door-apigateway
