global:
  # door-api config
  doorAPI:
    labels:
      # will be applied to pods and deployment
    protocol: http
    # internalServiceName: door-api-svc
    externalUrl: https://api.door.io
    heathCheck:
      image:
        name: docker.io/nginxinc/nginx-unprivileged
        version: latest
      endpoint: /api/v1/healthy
# set defaultCluster=true if cluster content control plane
defaultCluster: false
defaultClusterType: gke
doorOnboarding:
  labels:
    # will be applied to pods and deployment
  image:
    name: docker.io/beopenit/onboarding-operator-kubernetes
    version: v2.1.0-2023-08-24T16-46-45-4145d73b
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  #   limits:
  #     cpu: 1
  #     memory: 1Gi
doorCD:
  labels:
    # will be applied to pods and deployment
  # maxStagingReplicas: -22
  envs:
    - name: MAX_STAGING_REPLICAS
      value: "-1"
    - name: DOOR_AUTO_GEN_LISTENER
      value: "false"
    - name: INSECURE_REGISTRIES
      value: ""
    - name: DEFAULT_INTERNAL_GATEWAY_DOMAIN
      value: door.local
    - name: DEFAULT_TIMEOUT
      value: 30s
  image:
    name: docker.io/beopenit/door-cd-operator
    version: v2.2.0-2023-11-16T20-55-46-2de634ed
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 2
  #     memory: 2Gi

doorHelm:
  labels:
    # will be applied to pods and deployment
  # maxStagingReplicas: -22
  image:
    name: beopenit/door-helm
    version: 0.0.3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 2Gi

doorAgent:
  labels:
    # will be applied to pods and deployment
  metricServer: true
  image:
    name: docker.io/beopenit/door-agent
    version: v2.1.0-2023-08-24T16-45-21-03083bcc
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  #   limits:
  #     cpu: 1
  #     memory: 1Gi
  kafka:
    brokers: door-kafka-cluster-kafka-external-bootstrap:9094
  licence:
    uuid: aa
    key: |
      my-key
    crt: |
      my-crt
    ca: |
      my-ca
    # Overwrite licence secret: set keys uuid, user.key, user.crt and ca.crt
    # secret:
    #   name: my-licence

monitoring:
  include: true
  pvcSize: 15Gi

doorApiGateway:
  internal: 
    type: loadBalancer
    nodeSelector: node-role.kubernetes.io/ingress-door
    tolerationsKey: ingress-door
  external:
    type: loadBalancer
    nodeSelector: node-role.kubernetes.io/ingress-door
    tolerationsKey: ingress-door
