---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-operator-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onboarding-operator-kubernetes
  template:
    metadata:
      labels:
        name: onboarding-operator-kubernetes
    spec:
      serviceAccountName: onboarding-operator-kubernetes
      containers:
      - name: onboarding-operator-kubernetes
<<<<<<< HEAD
        image: beopenit/onboarding-operator-kubernetes:1.0.0-rc
=======
        image: beopenit/onboarding-operator-kubernetes:latest
>>>>>>> 2ad8d51d600200a23a31fe70a7bef1d68dcdeb06
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "onboarding-operator-kubernetes"